### ISSUE TITLE
useTrait re-render issue with effects

### ISSUE THREAD

**Issue by Ctrlmonster** [pmndrs/koota#20]
So I have this hook that I'm expecting to work, though it doesn't, maybe you could take a look @krispya – would you expect this to work?

```js
const dummyEntity = world.spawn();

export function useSingletonTrait(trait: Trait) {
  
  const entity = useQueryFirst(trait);
  console.log(entity); // <- becomes defined eventually

  const res = useTrait(entity ?? dummyEntity, trait);
  console.log(res); // <- stays undefined

  return res;
}
```

Ideally `dummyEntity` wouldn't be necessary if `useTrait` didn't error when passing undefined as the entity (and just returned undefined instead) but that's something we can discuss (though I think chaining `useQuery` + `useTrait` is a fair usecase).

`useTrait` implementation reacts to changing the target argument, so I'm not sure why this isn't working. Wondering if this is related to #13 

Edit: Copied the source and am seeing the event subscriptions are being properly redone, so it must be sth subtler.

**Comment by Ctrlmonster** [comment]
Not sure if this is desired, but this is what I'm doing locally for the moment which seems to work at first glance:

```js
// inside useTrait

 useEffect(() => {
    console.log("re-subscribe events");
    setValue(entity.get(trait)); // <- added this extra setState

    const onChangeUnsub = world.onChange(trait, (e) => {
      if (e === entity) setValue(e.get(trait));
    });

    const onAddUnsub = world.onAdd([trait], (e) => {
      if (e === entity) setValue(e.get(trait));
    });

    const onRemoveUnsub = world.onRemove([trait], (e) => {
      if (e === entity) setValue(undefined);
    });

    return () => {
      onChangeUnsub();
      onAddUnsub();
      onRemoveUnsub();
    };
  }, [entity, trait]);
```

**Comment by krispya** [comment]
Setting state on effect is a good fix. It catches cases where the state changes in the effect chain but before subscriptions. Go ahead and PR it.

The issue with allowing entity to be undefined or null is that you can no longer know if undefined returned from useTrait means the trait is no longer on the entity or the entity no longer exists. This ambiguity is not ideal, though maybe it isn’t a big deal if you can check the entity directly anyways?

So far I have structured my code so that there is one component that supplies an entity to its children and then the children (views) only get rendered if the entity exists. This is a nice pattern since it makes it impossible to get ambiguous state. However, maybe this is better as a best practice instead?

**Comment by Ctrlmonster** [comment]
PR is out. Can probably close this and #13 for now.

Yeah I remember from the space shooter – I think it's a fine pattern, just gets a bit annoying/verbose sometimes, if you really only have a single Component and need to split it up in two to get the entity first. I think it's likely fine in practice, as you mentioned it's possible to check trait/entity existence manually. It's not a super big deal for me, though I would prefer it, I think it's fine to keep it as it is and see if other people ask for it.
